### ISSUE TITLE
Part number of the new USB C port? 

### ISSUE THREAD

**Issue by krikkirk** [jamesturton/bose-qc35-usb-c#13]
Hey there, I noticed the most recent commit is about a new USB C port without the need of a shell mod. I was able to generate the gerber file and it seems there is a small difference. I am wondering if a new usb c part is available so it will fit the original casing.

**Comment by jamesturton** [comment]
The old USB C connector had some plastic support pins which needed removing. So it was the USB C connector its self which required modification. The casing will require cutting even with the new part due to the size of the USB C connector. The new part is also more widely available, rather than just being able to purchase from china.

**Comment by krikkirk** [comment]
Hi James, thanks for the explanation, it all makes sense now.
