### ISSUE TITLE
Has anyone built more than 1 of these? I'd be interested to buy 2-3 premade ones

### ISSUE THREAD

**Issue by spiriapbergeron** [jamesturton/bose-qc35-usb-c#14]
It seems like an awful lot of waste to order only 1 of these boards and 1 of each part and to assemble only 1 of these.

Where would I find little boards ones that are pre-built?

**Comment by jamesturton** [comment]
This project was created primarily for people who have experience in electronics construction and already have the tools and jellybean parts needed for assembling this. There are turnkey manufacturers who will do assembly for you, but as you might have found out this is uneconomical for a run of 1 board.

I have no intention of selling this as a product due to legal reasons regarding Bose and anyone else selling these boards will be violating the licence of which this project has been made public. While I have no intention of pursuing others who violate this licence by selling the boards that I have designed, Bose very well might have a different opinion to me and choose to take legal action regarding others making profit from their trademark.

That being said, I have heard of many people using the USB boards from the newer QC45 in their QC35 which fits just as good. I don't know of any official sources for the replacement USB boards for the QC45 but I know other have been able to buy them cheaply from China so I suggest you look there.
